language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  keep-history: true
  target_branch: master
  on:
    branch: dev
before_script:
  - "npm i -g gatsby"
  - "npm i"
  - "openssl aes-256-cbc -K $encrypted_53aac12992f3_key -iv $encrypted_53aac12992f3_iv -in github_deploy_key.enc -out github_deploy_key -d"
  - "chmod 600 github_deploy_key"
  - "eval $(ssh-agent -s)"
  - "ssh-add github_deploy_key"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
